### ISSUE TITLE
precision not working

### ISSUE THREAD

**Issue by mupsje** [ScratMan/HASmartThermostat#2]
Hi, great app, needed the PID
All works great, but the "precision" is not.
Cant operate in 0.1 steps.
Only in 0.5 steps

`- platform: smart_thermostat
  name: Woonkamer
  heater: switch.virtual_switch_virtual_vv
  target_sensor: sensor.average_woonkamer_temperatuur
  min_temp: 19
  max_temp: 24
  ac_mode: False
  target_temp: 20.4
  keep_alive:
    seconds: 60  
  kp : 30
  ki : 0.005
  kd : -24000
  pwm: 
    seconds: 300
  precision: 0.1
  away_temp: 19.3
  sleep_temp: 19.8
  comfort_temp: 21`

Please advice

**Comment by ScratMan** [comment]
Hi,
I reproduced the issue. Working on a fix.

**Comment by ScratMan** [comment]
This issue was linked to an old change in HA backend, the _precision_ parameter only sets the precision of the **displayed** sensor's temperature. With precision set to 0.5, if sensor's temperature is 21.2°C the thermostat will display 21, and if sensor's temperature increases to 21.3 the thermostat will display 21.5°C.
The target temperature precision is set by another parameter that was missing in my implementation.
This parameter is now added in release [2021.11.6](https://github.com/ScratMan/HASmartThermostat/releases/tag/2021.11.6), please use _target_temp_step_ in configuration file to set the adjustment step to your liking.
