### ISSUE TITLE
Issue after upgrade to 2024.11.0+1 -  helpers/translation.py:226

### ISSUE THREAD

**Issue by pos-ei-don** [ScratMan/HASmartThermostat#257]
```
Logger: homeassistant.helpers.translation
Quelle: helpers/translation.py:226
Erstmals aufgetreten: 6. November 2024 um 21:15:19 (1 Vorkommnisse)
Zuletzt protokolliert: 6. November 2024 um 21:15:19

Failed to load integration for translation: Integration 'smart_thermostat' not found.
```

Followed by 

```
Logger: homeassistant.config
Quelle: config.py:940
Erstmals aufgetreten: 6. November 2024 um 21:15:52 (1 Vorkommnisse)
Zuletzt protokolliert: 6. November 2024 um 21:15:52

Platform error: climate - Integration 'smart_thermostat' not found.
```

**Comment by pos-ei-don** [comment]
Same error after upgrade to 2024.11.1

**Comment by ScratMan** [comment]
Please check in HA logs if you see a message stating something like :
`something is blocking home assistant from wrapping up the start up phase. we're going to continue anyway. please report the following info...` followed by a long list of integration and an error message at the end.

I got it after updating to 2024.11.0 and 2024.11.1 and at the end it mentioned tasks from Google Sync and Google assistant. With this message I had a lot of things not working correctly, like HA being in english instead of french.
I went to the voice assistant settings page, disabled Google, restarted HA and the error was gone and everything went back to normal.
I then enabled Google again and the message came back.
I'm suspecting HA doesn't start correctly due to the Google connection.

**Comment by pos-ei-don** [comment]
I have no Google device enabled, nor do I find anything with blocking in the logs.
I cannot disable all extensions, because my house is connfigured as an electric Island and very Bad Things Happen if the central Computer does not send messages to the inverters.

**Comment by pos-ei-don** [comment]
I dwactivated some misrosoft  stuff, no success. But still no "blocking" or "wrapping" in my Logs, neither any Red nlmarkwd error

**Comment by HermesHonshappo** [comment]
Seems related to translation. Have you tried resetting HA to english, to see if this works?
I am on 2024.11, and have no issue with the smart_thermostat integration. But I have not changed the language

**Comment by pos-ei-don** [comment]
I changed this to englisch but nothing changed.

**Comment by ScratMan** [comment]
I can't reproduce the issue on my side. I saw it on another integration, but it disappeared and I don't know what the dev did to fix it

**Comment by pos-ei-don** [comment]
It works again after the last Updates. Thank you
