### ISSUE TITLE
Overrride PID on Boost mode

### ISSUE THREAD

**Issue by ejalal** [ScratMan/HASmartThermostat#32]
**Is your feature request related to a problem? Please describe.**
It would be nice to change the Boost mode from just setting the temperature to boost_temp, to completely ignore the PID calculations and behave like a generic_thermostat, and then back to "PID" mode once the boost_temp is reached.

This will allow to really boost the temperature temporarily and go back to normal

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ScratMan** [comment]
Hello, this might lead to strong overshoot, as the generic thermostat can't anticipate the fast temperature increase that will occur by leaving the heater on at full power for long period. However, it can already be achieved by setting a higher Kp gain in the settings, so that the target temperature step to boost temp leads to 100%. For example, for a 2°C step, a Kp gain  of 50 is enough. Then the Kd gain should be increased to progressively reduce the power during the temperature rise to limit the overshoot.

**Comment by ScratMan** [comment]
Hello, please test the [v2022.1.0](https://github.com/ScratMan/HASmartThermostat/releases/tag/2022.1.0) that includes optional settings to force PID off mode while in boost preset.
